import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderNavigation from "./component/navigation";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <div className="items-center justify-items-center mb-8">
        <HeaderNavigation/>

<div className="mt-4">
            <SignedOut> 
              <span className="mr-4">
                <SignInButton mode="modal" />
              </span>
              <span className="mr-4"> 

                <SignUpButton mode="modal" />
              </span>

            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
</div>
           
</div>
       
       <div className="grid items-center justify-items-center font-[family-name:var(--font-geist-mono)] text-4xl font-bold text-center mb-4">
       {children}

       </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
